# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phymail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymailsend',
            name='TO_address',
        ),
        migrations.AddField(
            model_name='mymailsend',
            name='Postcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymailsend',
            name='State',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mymailsend',
            name='TO_address_line_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mymailsend',
            name='TO_address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mymailsend',
            name='Town_City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
