# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phymail', '0002_auto_20160702_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymailsend',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
