# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-03 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phymail', '0003_mymailsend_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymailrecieve',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='mymailsend',
            options={'ordering': ['-timestamp']},
        ),
    ]
