# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-03 15:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('phymail', '0004_auto_20160703_2005'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mymailrecieve',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mymailsend',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
