# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-29 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Address_Line1', models.CharField(max_length=300)),
                ('Address_Line2', models.CharField(max_length=300)),
                ('Town_or_City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('PostCode', models.IntegerField()),
                ('Virtual_Office_Location', models.CharField(choices=[('Andheri', 'Andheri'), ('Borivali', 'Borivali'), ('Miraroad', 'Miraroad'), ('Virar', 'Virar')], max_length=2)),
                ('Active_user', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
