# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-06 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profille', '0003_auto_20160629_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Mobile_number',
            field=models.IntegerField(default=0),
        ),
    ]
