# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-03 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('Time_From', models.IntegerField()),
                ('Time_To', models.IntegerField()),
                ('Meeting_Date', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='meets',
            unique_together=set([('Time_From', 'Meeting_Date', 'Time_To')]),
        ),
    ]
