# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-03 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20160703_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meets',
            old_name='delete',
            new_name='deletee',
        ),
    ]
