# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20160704_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meets',
            name='Meeting_Date',
            field=models.DateField(),
        ),
    ]
