# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-07-08 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('End_Date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Task_Priority', models.CharField(choices=[('Important', 'Important'), ('Normal', 'Normal')], max_length=15)),
                ('Task_Topic', models.CharField(max_length=50)),
                ('Task_Details', models.TextField()),
                ('Task_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['End_Date'],
            },
        ),
    ]
